<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id .= $this->sliderId.'_'.$this->zoneconfig['conf']['id'];
    }
?>
<div id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>">
	<div class="npdc-heading">
		<h4>
			<i class="fa fa-columns"></i>
			<?= $this->translate('tr_MelisCmsSlider_manager')?>
		</h4>		
	</div>						
	<div class="pdc-content border-bottom">
		<?php 

		echo $this->form()->openTag($this->form);
		echo $this->melisFieldCollection($this->form);
		echo $this->form()->closeTag();

		?>					
		<br>
	</div>
</div>