-- MySQL Script generated by MySQL Workbench
-- 12/09/16 11:48:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `melis_cms_slider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_cms_slider` (
  `mcslide_id` INT NOT NULL AUTO_INCREMENT,
  `mcslide_name` VARCHAR(255) NOT NULL,
  `mcslide_page_id` INT NULL,
  `mcslide_date` DATETIME NULL,
  PRIMARY KEY (`mcslide_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melis_cms_slider_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_cms_slider_details` (
  `mcsdetail_id` INT NOT NULL AUTO_INCREMENT,
  `mcsdetail_mcslider_id` INT NOT NULL,
  `mcsdetail_status` TINYINT NOT NULL,
  `mcsdetail_title` VARCHAR(255) NULL,
  `mcsdetail_sub1` VARCHAR(255) NULL,
  `mcsdetail_sub2` VARCHAR(255) NULL,
  `mcsdetail_sub3` VARCHAR(255) NULL,
  `mcsdetail_link` LONGTEXT NULL,
  `mcsdetail_img` LONGTEXT NULL,
  `mcsdetail_order` INT NOT NULL,
  PRIMARY KEY (`mcsdetail_id`),
  INDEX `fk_melis_cms_slider_details_melis_cms_slider_idx` (`mcsdetail_mcslider_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
