<style>
    .carousel-inner .item {
        margin-bottom: initial;
    }
</style>

<div id="<?php echo $this->pluginId?>">
    <?php if (!empty($this->showSlider)){?>
    	<div class="container">
            <!-- data-bs-ride="carousel" -->
            <div id="cms-slider" class="carousel slide">
                <!-- Indicators -->
              	<ol class="carousel-indicators">
                    <li data-bs-target="#cms-slider" data-bs-slide-to="0" class="active"></li>
                    <li data-bs-target="#cms-slider" data-bs-slide-to="1"></li>
                    <li data-bs-target="#cms-slider" data-bs-slide-to="2"></li>
              	</ol>
              	
                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                	<?php foreach ($this->showSlider As $key => $val){?>
                    	<div class="carousel-item item <?php echo ($key == 0) ? 'active' : ''?>">
                          	<img src="<?php echo $val->mcsdetail_img?>" alt="...">
                          	<div class="carousel-caption">
                            	<h3><?php echo $val->mcsdetail_title ?> </h3>
       	 						<p><?php echo (!empty($val->mcsdetail_sub1)) ? $val->mcsdetail_sub1 : ''?></p>
                          	</div>
                        </div>
                    <?php }?>
                </div>
                
                <!-- Controls -->
                <a class="left carousel-control-prev" data-bs-target="#cms-slider" role="button" data-bs-slide="prev">
                    <!-- glyphicon glyphicon-chevron-left -->
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <!-- sr-only -->
                    <span class="visually-hidden">Previous</span>
                </a>
                <a class="right carousel-control-next" data-bs-target="#cms-slider" role="button" data-bs-slide="next">
                    <!-- glyphicon glyphicon-chevron-right -->
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <!-- sr-only -->
                    <span class="visually-hidden">Next</span>
                </a>
            </div>
        </div>
    <?php }else{?>
        <div class="alert alert-warning" role="alert">
        	No result
        </div>
    <?php }?>
</div>